# Generated by Django 3.0.3 on 2020-02-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0002_homeabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
