# Generated by Django 3.0.3 on 2020-02-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0003_auto_20200227_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=150)),
                ('partner_img', models.ImageField(upload_to='partner')),
            ],
        ),
    ]
