# Generated by Django 3.0.3 on 2020-02-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0006_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(upload_to='services'),
        ),
    ]
