# Generated by Django 3.0.3 on 2020-02-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0007_auto_20200229_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(),
        ),
    ]
