# Generated by Django 3.0.3 on 2020-03-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0010_homeclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Subject', models.CharField(max_length=150)),
                ('Message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
